### ISSUE TITLE
Blocage DSATUR sur une liste

### ISSUE THREAD

**Issue by Nambrok** [ProjetGrapheUVSQ2017/ProjetS6#23]
J'ai trouver un bug, quand un sommet est seul sans être relié et qu'on essaie de lancer un DSatur sur le graphe, le programme se bloque et l'on doit forcer sa fermeture.

(t'as peut-être oublié quelque chose et du coup tu te retrouves avec une boucle infinie quelque part quand la liste de sommet ne contient qu'un seul élément)

**Comment by madeleinevlt** [comment]
je sais ce que c'est, je fais ça tout de suite

**Comment by Nambrok** [comment]
Ok, cool, bon travail ;)

**Comment by madeleinevlt** [comment]
Il manquait un if :'(
